// <auto-generated />
using System;
using BankConsoleApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankConsoleApp.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankConsoleApp.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TryToEnterTimes")
                        .HasColumnType("int");

                    b.Property<int>("UserCardOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCardOwnerId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000.0,
                            CardNumber = "1234567812345678",
                            HolderName = "Ali Ahmadi",
                            IsActive = true,
                            Password = "password123",
                            TryToEnterTimes = 0,
                            UserCardOwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 1500.0,
                            CardNumber = "2345678923456789",
                            HolderName = "Maryam Mohammadi",
                            IsActive = true,
                            Password = "password456",
                            TryToEnterTimes = 0,
                            UserCardOwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Balance = 2000.0,
                            CardNumber = "3456789034567890",
                            HolderName = "Reza Hosseini",
                            IsActive = true,
                            Password = "password789",
                            TryToEnterTimes = 0,
                            UserCardOwnerId = 1
                        },
                        new
                        {
                            Id = 4,
                            Balance = 2500.0,
                            CardNumber = "4567890145678901",
                            HolderName = "Sara Karimi",
                            IsActive = true,
                            Password = "password101",
                            TryToEnterTimes = 0,
                            UserCardOwnerId = 1
                        },
                        new
                        {
                            Id = 5,
                            Balance = 3000.0,
                            CardNumber = "5678901256789012",
                            HolderName = "Hossein Soltani",
                            IsActive = true,
                            Password = "password202",
                            TryToEnterTimes = 0,
                            UserCardOwnerId = 1
                        });
                });

            modelBuilder.Entity("BankConsoleApp.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("DestinationCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("forCardId")
                        .HasColumnType("int");

                    b.Property<bool>("isSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("TransactionId");

                    b.HasIndex("forCardId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankConsoleApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Ali",
                            Lastname = "Ahmadi",
                            Password = "ali123",
                            Username = "ali.ahmadi",
                            phone = "09197980113"
                        });
                });

            modelBuilder.Entity("BankConsoleApp.Entities.Card", b =>
                {
                    b.HasOne("BankConsoleApp.Entities.User", "UserCardOwner")
                        .WithMany("CardList")
                        .HasForeignKey("UserCardOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCardOwner");
                });

            modelBuilder.Entity("BankConsoleApp.Entities.Transaction", b =>
                {
                    b.HasOne("BankConsoleApp.Entities.Card", "forCard")
                        .WithMany("transactions")
                        .HasForeignKey("forCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("forCard");
                });

            modelBuilder.Entity("BankConsoleApp.Entities.Card", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("BankConsoleApp.Entities.User", b =>
                {
                    b.Navigation("CardList");
                });
#pragma warning restore 612, 618
        }
    }
}
